version: "3"

tasks:
  default:
    desc: "Show all available tasks"
    cmds:
      - task --list-all

  # ------------------------------
  # Docker Service Operations
  # ------------------------------
  docker:auth-service:
    desc: "Run the Auth service Docker container"
    cmds:
      - ./tools/scripts/docker.sh auth-service

  docker:user-service:
    desc: "Run the User service Docker container"
    cmds:
      - ./tools/scripts/docker.sh user-service

  docker:security-service:
    desc: "Run the Security service Docker container"
    cmds:
      - ./tools/scripts/docker.sh security-service

  docker:stock-service:
    desc: "Run the Stock service Docker container"
    cmds:
      - ./tools/scripts/docker.sh stock-service

  docker:api-gateway:
    desc: "Run the API Gateway Docker container"
    cmds:
      - ./tools/scripts/docker.sh api-gateway

  # ------------------------------
  # Docker Lifecycle Operations
  # ------------------------------
  docker:run:
    desc: "Run all Docker containers (optionally with monitoring)"
    cmds:
      - ./tools/scripts/docker.sh run "{{.monitoring}}"

  docker:build:
    desc: "Build all Docker images"
    cmds:
      - ./tools/scripts/docker.sh build

  docker:start:
    desc: "Start all stopped Docker containers"
    cmds:
      - ./tools/scripts/docker.sh start

  docker:pause:
    desc: "Pause all running Docker containers"
    cmds:
      - ./tools/scripts/docker.sh pause

  docker:stop:
    desc: "Stop all running Docker containers"
    cmds:
      - ./tools/scripts/docker.sh stop

  docker:status:
    desc: "Show status of all Docker containers"
    cmds:
      - ./tools/scripts/docker.sh status

  docker:logs:
    desc: "Show logs from all Docker containers"
    cmds:
      - ./tools/scripts/docker.sh logs

  docker:rm-volumes:
    desc: "Remove all Docker volumes"
    cmds:
      - ./tools/scripts/docker.sh rm-volumes

  docker:prune:
    desc: "Prune unused Docker resources"
    cmds:
      - ./tools/scripts/docker.sh prune

  docker:clean:
    desc: "Stop containers, prune resources, and remove volumes"
    deps:
      - docker:stop
      - docker:prune
      - docker:rm-volumes

  docker:reset:
    desc: "Clean, build, and run Docker containers from scratch"
    deps:
      - docker:clean
      - docker:build
      - docker:run

  # ------------------------------
  # Database Migrations Operations
  # ------------------------------

  migrate:up:
    desc: "Apply all pending database migrations"
    cmds:
      - ./tools/scripts/migrate.sh up

  migrate:down:
    desc: "Rollback the last database migration"
    cmds:
      - ./tools/scripts/migrate.sh down

  migrate:status:
    desc: "Show current database migration status"
    cmds:
      - ./tools/scripts/migrate.sh status

  migrate:create:
    desc: "Create a new database migration (requires db and name)"
    cmds:
      - ./tools/scripts/migrate.sh create "{{.db}}" "{{.name}}"

  # ------------------------------
  # Codegen Operations
  # ------------------------------

  generate:
    desc: "Generate code (GraphQL/SQLc/protobuf)"
    cmds:
      - ./tools/scripts/codegen.sh generate "{{.codegen}}" "{{.service}}"

  # ------------------------------
  # Database Seed Operations
  # ------------------------------

  seed:
    desc: "Seed the database (use db=all or specify a database)"
    cmds:
      - cd tools/seeder && go run main.go --db "{{.db}}"

  # ------------------------------
  # Kubernetes Operations
  # ------------------------------

  kube:start:
    desc: "Start Kubernetes cluster"
    cmds:
      - ./tools/scripts/k8s.sh start

  kube:stop:
    desc: "Stop Kubernetes cluster"
    cmds:
      - minikube stop -p fafnir-cluster

  kube:deploy:
    desc: "Deploy a pod to Kubernetes (usage: pod=<name> task kube:deploy)"
    cmds:
      - ./tools/scripts/k8s.sh deploy "{{.pod}}"

  kube:delete:
    desc: "Delete Kubernetes resources"
    cmds:
      - ./tools/scripts/k8s.sh delete

  kube:reset:
    desc: "Reset a pod or all Kubernetes resources"
    cmds:
      - ./tools/scripts/k8s.sh reset "{{.pod}}"

  kube:status:
    desc: "Show Kubernetes cluster status"
    cmds:
      - ./tools/scripts/k8s.sh status

  kube:nodes:
    desc: "List Kubernetes nodes"
    cmds:
      - ./tools/scripts/k8s.sh nodes

  kube:pods:
    desc: "List Kubernetes pods"
    cmds:
      - ./tools/scripts/k8s.sh pods

  kube:svc:
    desc: "List Kubernetes services"
    cmds:
      - ./tools/scripts/k8s.sh svc

  kube:deployments:
    desc: "List Kubernetes deployments"
    cmds:
      - ./tools/scripts/k8s.sh deployments

  kube:logs:
    desc: "Show logs for a specific pod (requires pod variable)"
    cmds:
      - ./tools/scripts/k8s.sh logs "{{.pod}}"

  kube:dashboard:
    desc: "Open Kubernetes dashboard"
    cmds:
      - minikube dashboard -p fafnir-cluster

  kube:ssh:
    desc: "SSH into Kubernetes cluster node"
    cmds:
      - minikube ssh -p fafnir-cluster

  kube:forward:
    desc: "Forward local port to pod (requires pod variable)"
    cmds:
      - ./tools/scripts/k8s.sh forward "{{.pod}}"

  kube:tunnel:
    desc: "Create Minikube tunnel for LoadBalancer services"
    cmds:
      - minikube tunnel -p fafnir-cluster