package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fafnir/api-gateway/graph/generated"
	"fafnir/api-gateway/graph/model"
	"fmt"
	"log"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginRequest) (*model.LoginResponse, error) {
	loginResp, err := r.AuthClient.Login(ctx, input)
	if err != nil {
		log.Printf("Error calling auth service for login: %v", err)
		return nil, fmt.Errorf("authentication failed: %w", err)
	}

	return loginResp, nil
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterRequest) (*model.RegisterResponse, error) {
	// for now this only calls the auth service, but it should also call the user service to create a user profile too
	registerResp, err := r.AuthClient.Register(ctx, input)
	if err != nil {
		log.Printf("Error calling auth service for registration: %v", err)
		return nil, fmt.Errorf("registration failed: %w", err)
	}

	return registerResp, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
