package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fafnir/api-gateway/graph/generated"
	"fafnir/api-gateway/graph/model"
	"fmt"
	"log"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.LoginResponse, error) {
	loginResp, err := r.AuthClient.Login(ctx, input.Username, input.Password)
	if err != nil {
		log.Printf("Error calling auth service for login: %v", err)
		return nil, fmt.Errorf("authentication failed: %w", err)
	}

	code := int32(loginResp.Code)

	return &model.LoginResponse{
		Code:    &code,
		Message: &loginResp.Message,
	}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
