package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fafnir/api-gateway/graph/model"
	"fmt"
)

// CheckPermission is the resolver for the CheckPermission field.
func (r *queryResolver) CheckPermission(ctx context.Context, request model.HasPermissionRequest) (*model.HasPermissionResponse, error) {
	res, err := r.SecurityClient.CheckPermission(ctx, request.UserID, request.Permission)
	if err != nil {
		return nil, fmt.Errorf("failed to communicate with security service: %w", err)
	}

	return &model.HasPermissionResponse{
		HasPermission:  res.HasPermission,
		PermissionCode: res.PermissionCode,
	}, nil
}
