package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fafnir/api-gateway/graph/model"
	"fmt"
)

// GetStockMetadata is the resolver for the getStockMetadata field.
func (r *queryResolver) GetStockMetadata(ctx context.Context, symbol string) (*model.StockMetadataResponse, error) {
	resp, err := r.StockClient.GetStockMetadata(ctx, symbol)
	if err != nil {
		return nil, fmt.Errorf("failed to get stock metadata: %w", err)
	}

	return &model.StockMetadataResponse{
		Code: resp.Code,
		Data: resp.Data,
	}, nil
}
