package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fafnir/api-gateway/graph/model"
	"fmt"
)

// GetProfileData is the resolver for the getProfileData field.
func (r *queryResolver) GetProfileData(ctx context.Context, request model.ProfileDataRequest) (*model.ProfileDataResponse, error) {
	res, err := r.UserClient.GetProfileData(ctx, request.UserID)
	if err != nil {
		return nil, fmt.Errorf("failed to communicate with user service: %w", err)
	}

	return res, nil
}
