services:
  db:
    image: fafnir-postgres-db
    build:
      context: .
      dockerfile: db/Dockerfile
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  api-gateway:
    build:
      context: ..
      dockerfile: services/api-gateway/Dockerfile
    volumes:
      - ../services/api-gateway:/app/services/api-gateway
      - ../shared:/app/shared
    depends_on:
      - auth-service
      - user-service
    ports:
      - "8080:8080"

  auth-service:
    build:
      context: ..
      dockerfile: services/auth-service/Dockerfile
    volumes:
        - ../services/auth-service:/app/services/auth-service
        - ../shared:/app/shared

  user-service:
    build:
      context: ..
      dockerfile: services/user-service/Dockerfile
    volumes:
      - ../services/user-service:/app/services/user-service
      - ../shared:/app/shared

  web-app:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../frontend:/app

volumes:
  pgdata: