package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fafnir/api-gateway/graph/model"
	"fafnir/api-gateway/internal/middleware"
	"fafnir/api-gateway/internal/rbac"
)

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, request model.CreateOrderRequest) (*model.CreateOrderResponse, error) {
	userID, err := middleware.GetUserIdFromContext(ctx)
	if err != nil {
		return nil, err
	}

	_, err = r.SecurityClient.CheckPermission(ctx, userID.String(), rbac.OrderStocks)
	if err != nil {
		return nil, err
	}

	resp, err := r.OrderClient.InsertOrder(ctx, userID.String(), request)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// CancelOrder is the resolver for the cancelOrder field.
func (r *mutationResolver) CancelOrder(ctx context.Context, orderID string) (*model.CancelOrderResponse, error) {
	userID, err := middleware.GetUserIdFromContext(ctx)
	if err != nil {
		return nil, err
	}

	_, err = r.SecurityClient.CheckPermission(ctx, userID.String(), rbac.OrderStocks)
	if err != nil {
		return nil, err
	}

	resp, err := r.OrderClient.CancelOrder(ctx, orderID, userID.String())
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetOrders is the resolver for the getOrders field.
func (r *queryResolver) GetOrders(ctx context.Context) (*model.OrdersResponse, error) {
	userID, err := middleware.GetUserIdFromContext(ctx)
	if err != nil {
		return nil, err
	}

	_, err = r.SecurityClient.CheckPermission(ctx, userID.String(), rbac.OrderStocks)
	if err != nil {
		return nil, err
	}

	resp, err := r.OrderClient.GetOrders(ctx, userID.String())
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetOrderByOrderID is the resolver for the getOrderByOrderID field.
func (r *queryResolver) GetOrderByOrderID(ctx context.Context, request model.GetOrderByIDRequest) (*model.GetOrderByIDResponse, error) {
	userID, err := middleware.GetUserIdFromContext(ctx)
	if err != nil {
		return nil, err
	}

	_, err = r.SecurityClient.CheckPermission(ctx, userID.String(), rbac.OrderStocks)
	if err != nil {
		return nil, err
	}

	resp, err := r.OrderClient.GetOrderByOrderID(ctx, request.OrderID)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}
