package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fafnir/api-gateway/graph/model"
	"fafnir/api-gateway/internal/middleware"
)

// CreateAccount is the resolver for the createAccount field.
func (r *mutationResolver) CreateAccount(ctx context.Context, request model.CreateAccountRequest) (*model.CreateAccountResponse, error) {
	userID, err := middleware.GetUserIdFromContext(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.PortfolioClient.CreateAccount(ctx, userID.String(), request)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// AddToWatchlist is the resolver for the addToWatchlist field.
func (r *mutationResolver) AddToWatchlist(ctx context.Context, request model.AddToWatchlistRequest) (*model.AddToWatchlistResponse, error) {
	userID, err := middleware.GetUserIdFromContext(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.PortfolioClient.AddToWatchlist(ctx, userID.String(), request)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// RemoveFromWatchlist is the resolver for the removeFromWatchlist field.
func (r *mutationResolver) RemoveFromWatchlist(ctx context.Context, request model.RemoveFromWatchlistRequest) (*model.RemoveFromWatchlistResponse, error) {
	userID, err := middleware.GetUserIdFromContext(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.PortfolioClient.RemoveFromWatchlist(ctx, userID.String(), request)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// DeleteAccount is the resolver for the deleteAccount field.
func (r *mutationResolver) DeleteAccount(ctx context.Context, accountID string) (bool, error) {
	return r.PortfolioClient.DeleteAccount(ctx, accountID)
}

// GetPortfolioSummary is the resolver for the getPortfolioSummary field.
func (r *queryResolver) GetPortfolioSummary(ctx context.Context) (*model.GetPortfolioSummaryResponse, error) {
	userID, err := middleware.GetUserIdFromContext(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.PortfolioClient.GetPortfolioSummary(ctx, userID.String())
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetHoldings is the resolver for the getHoldings field.
func (r *queryResolver) GetHoldings(ctx context.Context, request model.GetHoldingsRequest) (*model.GetHoldingsResponse, error) {
	resp, err := r.PortfolioClient.GetHoldings(ctx, request)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetHolding is the resolver for the getHolding field.
func (r *queryResolver) GetHolding(ctx context.Context, request model.GetHoldingRequest) (*model.GetHoldingResponse, error) {
	resp, err := r.PortfolioClient.GetHolding(ctx, request)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetWatchlist is the resolver for the getWatchlist field.
func (r *queryResolver) GetWatchlist(ctx context.Context) (*model.GetWatchlistResponse, error) {
	userID, err := middleware.GetUserIdFromContext(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.PortfolioClient.GetWatchlist(ctx, userID.String())
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetTransactions is the resolver for the getTransactions field.
func (r *queryResolver) GetTransactions(ctx context.Context, request model.GetTransactionsRequest) (*model.GetTransactionsResponse, error) {
	resp, err := r.PortfolioClient.GetTransactions(ctx, request)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}
