package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fafnir/api-gateway/graph/model"
	"fafnir/api-gateway/internal/middleware"
	"fmt"
)

// CheckPermission is the resolver for the CheckPermission field.
func (r *queryResolver) CheckPermission(ctx context.Context, request model.HasPermissionRequest) (*model.HasPermissionResponse, error) {
	userID, err := middleware.GetUserIdFromContext(ctx)
	if err != nil {
		return nil, err
	}

	res, err := r.SecurityClient.CheckPermission(ctx, userID.String(), request.Permission)
	if err != nil {
		return nil, fmt.Errorf("failed to communicate with security service: %w", err)
	}

	return res, nil
}
