package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fafnir/api-gateway/graph/model"
	"fafnir/api-gateway/internal/middleware"
	"fafnir/api-gateway/internal/rbac"
)

// GetStockMetadata is the resolver for the getStockMetadata field.
func (r *queryResolver) GetStockMetadata(ctx context.Context, symbol string) (*model.StockMetadataResponse, error) {
	userID, err := middleware.GetUserIdFromContext(ctx)
	if err != nil {
		return nil, err
	}

	_, err = r.SecurityClient.CheckPermission(ctx, userID.String(), rbac.ViewStocks)
	if err != nil {
		return nil, err
	}

	resp, err := r.StockClient.GetStockMetadata(ctx, symbol)
	if err != nil {
		return nil, err
	}

	return &model.StockMetadataResponse{
		Code: resp.Code,
		Data: resp.Data,
	}, nil
}

// GetStockQuote is the resolver for the getStockQuote field.
func (r *queryResolver) GetStockQuote(ctx context.Context, symbol string) (*model.StockQuoteResponse, error) {
	userID, err := middleware.GetUserIdFromContext(ctx)
	if err != nil {
		return nil, err
	}

	_, err = r.SecurityClient.CheckPermission(ctx, userID.String(), rbac.ViewStocks)
	if err != nil {
		return nil, err
	}

	resp, err := r.StockClient.GetStockQuote(ctx, symbol)
	if err != nil {
		return nil, err
	}

	return &model.StockQuoteResponse{
		Code: resp.Code,
		Data: resp.Data,
	}, nil
}

// GetStockHistoricalData is the resolver for the getStockHistoricalData field.
func (r *queryResolver) GetStockHistoricalData(ctx context.Context, symbol string, period *string) (*model.StockHistoricalDataResponse, error) {
	userID, err := middleware.GetUserIdFromContext(ctx)
	if err != nil {
		return nil, err
	}

	_, err = r.SecurityClient.CheckPermission(ctx, userID.String(), rbac.ViewStocks)
	if err != nil {
		return nil, err
	}

	resp, err := r.StockClient.GetStockHistoricalData(ctx, symbol, *period)
	if err != nil {
		return nil, err
	}

	return &model.StockHistoricalDataResponse{
		Code: resp.Code,
		Data: resp.Data,
	}, nil
}

// GetStockQuoteBatch is the resolver for the getStockQuoteBatch field.
func (r *queryResolver) GetStockQuoteBatch(ctx context.Context, symbols []string) (*model.StockQuoteBatchResponse, error) {
	userID, err := middleware.GetUserIdFromContext(ctx)
	if err != nil {
		return nil, err
	}

	_, err = r.SecurityClient.CheckPermission(ctx, userID.String(), rbac.ViewStocks)
	if err != nil {
		return nil, err
	}

	resp, err := r.StockClient.GetStockQuoteBatch(ctx, symbols)
	if err != nil {
		return nil, err
	}

	return &model.StockQuoteBatchResponse{
		Code: resp.Code,
		Data: resp.Data,
	}, nil
}
