package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fafnir/api-gateway/graph/model"
	"fafnir/api-gateway/internal/middleware"
	"fafnir/api-gateway/internal/rbac"
)

// GetProfileData is the resolver for the getProfileData field.
func (r *queryResolver) GetProfileData(ctx context.Context) (*model.ProfileDataResponse, error) {
	userID, err := middleware.GetUserIdFromContext(ctx)
	if err != nil {
		return nil, err
	}

	_, err = r.SecurityClient.CheckPermission(ctx, userID.String(), rbac.ManageOwnProfile)
	if err != nil {
		return nil, err
	}

	res, err := r.UserClient.GetProfileData(ctx, userID.String())
	if err != nil {
		return nil, err
	}

	return res, nil
}
