package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fafnir/api-gateway/graph/model"
)

// GetProfileData is the resolver for the getProfileData field.
func (r *queryResolver) GetProfileData(ctx context.Context, userID string) (*model.ProfileDataResponse, error) {
	res, err := r.UserClient.GetProfileData(ctx, userID)
	if err != nil {
		return nil, err
	}

	return res, nil
}
