// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: stock.proto

package pb

import (
	base "fafnir/shared/pb/base"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StockMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Symbol           string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Currency         string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Exchange         string                 `protobuf:"bytes,4,opt,name=exchange,proto3" json:"exchange,omitempty"`
	ExchangeFullName string                 `protobuf:"bytes,5,opt,name=exchange_full_name,json=exchangeFullName,proto3" json:"exchange_full_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StockMetadata) Reset() {
	*x = StockMetadata{}
	mi := &file_stock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockMetadata) ProtoMessage() {}

func (x *StockMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockMetadata.ProtoReflect.Descriptor instead.
func (*StockMetadata) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{0}
}

func (x *StockMetadata) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *StockMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StockMetadata) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *StockMetadata) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *StockMetadata) GetExchangeFullName() string {
	if x != nil {
		return x.ExchangeFullName
	}
	return ""
}

type StockQuote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	LastPrice     float64                `protobuf:"fixed64,2,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"`
	OpenPrice     float64                `protobuf:"fixed64,3,opt,name=open_price,json=openPrice,proto3" json:"open_price,omitempty"`
	PreviousClose float64                `protobuf:"fixed64,4,opt,name=previous_close,json=previousClose,proto3" json:"previous_close,omitempty"`
	DayLow        float64                `protobuf:"fixed64,5,opt,name=day_low,json=dayLow,proto3" json:"day_low,omitempty"`
	DayHigh       float64                `protobuf:"fixed64,6,opt,name=day_high,json=dayHigh,proto3" json:"day_high,omitempty"`
	YearLow       float64                `protobuf:"fixed64,7,opt,name=year_low,json=yearLow,proto3" json:"year_low,omitempty"`
	YearHigh      float64                `protobuf:"fixed64,8,opt,name=year_high,json=yearHigh,proto3" json:"year_high,omitempty"`
	Volume        int64                  `protobuf:"varint,9,opt,name=volume,proto3" json:"volume,omitempty"`
	MarketCap     float64                `protobuf:"fixed64,10,opt,name=market_cap,json=marketCap,proto3" json:"market_cap,omitempty"`
	Change        float64                `protobuf:"fixed64,11,opt,name=change,proto3" json:"change,omitempty"`
	ChangePct     float64                `protobuf:"fixed64,12,opt,name=change_pct,json=changePct,proto3" json:"change_pct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockQuote) Reset() {
	*x = StockQuote{}
	mi := &file_stock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockQuote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockQuote) ProtoMessage() {}

func (x *StockQuote) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockQuote.ProtoReflect.Descriptor instead.
func (*StockQuote) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{1}
}

func (x *StockQuote) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *StockQuote) GetLastPrice() float64 {
	if x != nil {
		return x.LastPrice
	}
	return 0
}

func (x *StockQuote) GetOpenPrice() float64 {
	if x != nil {
		return x.OpenPrice
	}
	return 0
}

func (x *StockQuote) GetPreviousClose() float64 {
	if x != nil {
		return x.PreviousClose
	}
	return 0
}

func (x *StockQuote) GetDayLow() float64 {
	if x != nil {
		return x.DayLow
	}
	return 0
}

func (x *StockQuote) GetDayHigh() float64 {
	if x != nil {
		return x.DayHigh
	}
	return 0
}

func (x *StockQuote) GetYearLow() float64 {
	if x != nil {
		return x.YearLow
	}
	return 0
}

func (x *StockQuote) GetYearHigh() float64 {
	if x != nil {
		return x.YearHigh
	}
	return 0
}

func (x *StockQuote) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *StockQuote) GetMarketCap() float64 {
	if x != nil {
		return x.MarketCap
	}
	return 0
}

func (x *StockQuote) GetChange() float64 {
	if x != nil {
		return x.Change
	}
	return 0
}

func (x *StockQuote) GetChangePct() float64 {
	if x != nil {
		return x.ChangePct
	}
	return 0
}

type StockHistoricalData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	OpenPrice     float64                `protobuf:"fixed64,3,opt,name=open_price,json=openPrice,proto3" json:"open_price,omitempty"`
	HighPrice     float64                `protobuf:"fixed64,4,opt,name=high_price,json=highPrice,proto3" json:"high_price,omitempty"`
	LowPrice      float64                `protobuf:"fixed64,5,opt,name=low_price,json=lowPrice,proto3" json:"low_price,omitempty"`
	ClosePrice    float64                `protobuf:"fixed64,6,opt,name=close_price,json=closePrice,proto3" json:"close_price,omitempty"`
	Volume        int64                  `protobuf:"varint,7,opt,name=volume,proto3" json:"volume,omitempty"`
	Change        float64                `protobuf:"fixed64,8,opt,name=change,proto3" json:"change,omitempty"`
	ChangePct     float64                `protobuf:"fixed64,9,opt,name=change_pct,json=changePct,proto3" json:"change_pct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockHistoricalData) Reset() {
	*x = StockHistoricalData{}
	mi := &file_stock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockHistoricalData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockHistoricalData) ProtoMessage() {}

func (x *StockHistoricalData) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockHistoricalData.ProtoReflect.Descriptor instead.
func (*StockHistoricalData) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{2}
}

func (x *StockHistoricalData) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *StockHistoricalData) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *StockHistoricalData) GetOpenPrice() float64 {
	if x != nil {
		return x.OpenPrice
	}
	return 0
}

func (x *StockHistoricalData) GetHighPrice() float64 {
	if x != nil {
		return x.HighPrice
	}
	return 0
}

func (x *StockHistoricalData) GetLowPrice() float64 {
	if x != nil {
		return x.LowPrice
	}
	return 0
}

func (x *StockHistoricalData) GetClosePrice() float64 {
	if x != nil {
		return x.ClosePrice
	}
	return 0
}

func (x *StockHistoricalData) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *StockHistoricalData) GetChange() float64 {
	if x != nil {
		return x.Change
	}
	return 0
}

func (x *StockHistoricalData) GetChangePct() float64 {
	if x != nil {
		return x.ChangePct
	}
	return 0
}

type GetStockMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockMetadataRequest) Reset() {
	*x = GetStockMetadataRequest{}
	mi := &file_stock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockMetadataRequest) ProtoMessage() {}

func (x *GetStockMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetStockMetadataRequest) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{3}
}

func (x *GetStockMetadataRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type GetStockQuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockQuoteRequest) Reset() {
	*x = GetStockQuoteRequest{}
	mi := &file_stock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockQuoteRequest) ProtoMessage() {}

func (x *GetStockQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockQuoteRequest.ProtoReflect.Descriptor instead.
func (*GetStockQuoteRequest) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{4}
}

func (x *GetStockQuoteRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type GetStockHistoricalDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"` // e.g., "1D", "1W", "1M", "3M", "6M", "1Y", "2Y", "5Y", "MAX"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockHistoricalDataRequest) Reset() {
	*x = GetStockHistoricalDataRequest{}
	mi := &file_stock_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockHistoricalDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockHistoricalDataRequest) ProtoMessage() {}

func (x *GetStockHistoricalDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockHistoricalDataRequest.ProtoReflect.Descriptor instead.
func (*GetStockHistoricalDataRequest) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{5}
}

func (x *GetStockHistoricalDataRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetStockHistoricalDataRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type GetStockQuoteBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockQuoteBatchRequest) Reset() {
	*x = GetStockQuoteBatchRequest{}
	mi := &file_stock_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockQuoteBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockQuoteBatchRequest) ProtoMessage() {}

func (x *GetStockQuoteBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockQuoteBatchRequest.ProtoReflect.Descriptor instead.
func (*GetStockQuoteBatchRequest) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{6}
}

func (x *GetStockQuoteBatchRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

type GetStockMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *StockMetadata         `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Code          base.ErrorCode         `protobuf:"varint,2,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockMetadataResponse) Reset() {
	*x = GetStockMetadataResponse{}
	mi := &file_stock_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockMetadataResponse) ProtoMessage() {}

func (x *GetStockMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetStockMetadataResponse) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{7}
}

func (x *GetStockMetadataResponse) GetData() *StockMetadata {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetStockMetadataResponse) GetCode() base.ErrorCode {
	if x != nil {
		return x.Code
	}
	return base.ErrorCode(0)
}

type GetStockQuoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *StockQuote            `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Code          base.ErrorCode         `protobuf:"varint,2,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockQuoteResponse) Reset() {
	*x = GetStockQuoteResponse{}
	mi := &file_stock_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockQuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockQuoteResponse) ProtoMessage() {}

func (x *GetStockQuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockQuoteResponse.ProtoReflect.Descriptor instead.
func (*GetStockQuoteResponse) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{8}
}

func (x *GetStockQuoteResponse) GetData() *StockQuote {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetStockQuoteResponse) GetCode() base.ErrorCode {
	if x != nil {
		return x.Code
	}
	return base.ErrorCode(0)
}

type GetStockHistoricalDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*StockHistoricalData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Code          base.ErrorCode         `protobuf:"varint,2,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockHistoricalDataResponse) Reset() {
	*x = GetStockHistoricalDataResponse{}
	mi := &file_stock_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockHistoricalDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockHistoricalDataResponse) ProtoMessage() {}

func (x *GetStockHistoricalDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockHistoricalDataResponse.ProtoReflect.Descriptor instead.
func (*GetStockHistoricalDataResponse) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{9}
}

func (x *GetStockHistoricalDataResponse) GetData() []*StockHistoricalData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetStockHistoricalDataResponse) GetCode() base.ErrorCode {
	if x != nil {
		return x.Code
	}
	return base.ErrorCode(0)
}

type GetStockQuoteBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*StockQuote          `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Code          base.ErrorCode         `protobuf:"varint,2,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockQuoteBatchResponse) Reset() {
	*x = GetStockQuoteBatchResponse{}
	mi := &file_stock_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockQuoteBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockQuoteBatchResponse) ProtoMessage() {}

func (x *GetStockQuoteBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockQuoteBatchResponse.ProtoReflect.Descriptor instead.
func (*GetStockQuoteBatchResponse) Descriptor() ([]byte, []int) {
	return file_stock_proto_rawDescGZIP(), []int{10}
}

func (x *GetStockQuoteBatchResponse) GetData() []*StockQuote {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetStockQuoteBatchResponse) GetCode() base.ErrorCode {
	if x != nil {
		return x.Code
	}
	return base.ErrorCode(0)
}

var File_stock_proto protoreflect.FileDescriptor

const file_stock_proto_rawDesc = "" +
	"\n" +
	"\vstock.proto\x12\x05stock\x1a\n" +
	"base.proto\"\xa1\x01\n" +
	"\rStockMetadata\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x1a\n" +
	"\bexchange\x18\x04 \x01(\tR\bexchange\x12,\n" +
	"\x12exchange_full_name\x18\x05 \x01(\tR\x10exchangeFullName\"\xe3\x02\n" +
	"\n" +
	"StockQuote\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"last_price\x18\x02 \x01(\x01R\tlastPrice\x12\x1d\n" +
	"\n" +
	"open_price\x18\x03 \x01(\x01R\topenPrice\x12%\n" +
	"\x0eprevious_close\x18\x04 \x01(\x01R\rpreviousClose\x12\x17\n" +
	"\aday_low\x18\x05 \x01(\x01R\x06dayLow\x12\x19\n" +
	"\bday_high\x18\x06 \x01(\x01R\adayHigh\x12\x19\n" +
	"\byear_low\x18\a \x01(\x01R\ayearLow\x12\x1b\n" +
	"\tyear_high\x18\b \x01(\x01R\byearHigh\x12\x16\n" +
	"\x06volume\x18\t \x01(\x03R\x06volume\x12\x1d\n" +
	"\n" +
	"market_cap\x18\n" +
	" \x01(\x01R\tmarketCap\x12\x16\n" +
	"\x06change\x18\v \x01(\x01R\x06change\x12\x1d\n" +
	"\n" +
	"change_pct\x18\f \x01(\x01R\tchangePct\"\x8c\x02\n" +
	"\x13StockHistoricalData\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x1d\n" +
	"\n" +
	"open_price\x18\x03 \x01(\x01R\topenPrice\x12\x1d\n" +
	"\n" +
	"high_price\x18\x04 \x01(\x01R\thighPrice\x12\x1b\n" +
	"\tlow_price\x18\x05 \x01(\x01R\blowPrice\x12\x1f\n" +
	"\vclose_price\x18\x06 \x01(\x01R\n" +
	"closePrice\x12\x16\n" +
	"\x06volume\x18\a \x01(\x03R\x06volume\x12\x16\n" +
	"\x06change\x18\b \x01(\x01R\x06change\x12\x1d\n" +
	"\n" +
	"change_pct\x18\t \x01(\x01R\tchangePct\"1\n" +
	"\x17GetStockMetadataRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\".\n" +
	"\x14GetStockQuoteRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"O\n" +
	"\x1dGetStockHistoricalDataRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\"5\n" +
	"\x19GetStockQuoteBatchRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\"i\n" +
	"\x18GetStockMetadataResponse\x12(\n" +
	"\x04data\x18\x01 \x01(\v2\x14.stock.StockMetadataR\x04data\x12#\n" +
	"\x04code\x18\x02 \x01(\x0e2\x0f.base.ErrorCodeR\x04code\"c\n" +
	"\x15GetStockQuoteResponse\x12%\n" +
	"\x04data\x18\x01 \x01(\v2\x11.stock.StockQuoteR\x04data\x12#\n" +
	"\x04code\x18\x02 \x01(\x0e2\x0f.base.ErrorCodeR\x04code\"u\n" +
	"\x1eGetStockHistoricalDataResponse\x12.\n" +
	"\x04data\x18\x01 \x03(\v2\x1a.stock.StockHistoricalDataR\x04data\x12#\n" +
	"\x04code\x18\x02 \x01(\x0e2\x0f.base.ErrorCodeR\x04code\"h\n" +
	"\x1aGetStockQuoteBatchResponse\x12%\n" +
	"\x04data\x18\x01 \x03(\v2\x11.stock.StockQuoteR\x04data\x12#\n" +
	"\x04code\x18\x02 \x01(\x0e2\x0f.base.ErrorCodeR\x04code2\xf1\x02\n" +
	"\fStockService\x12S\n" +
	"\x10GetStockMetadata\x12\x1e.stock.GetStockMetadataRequest\x1a\x1f.stock.GetStockMetadataResponse\x12J\n" +
	"\rGetStockQuote\x12\x1b.stock.GetStockQuoteRequest\x1a\x1c.stock.GetStockQuoteResponse\x12e\n" +
	"\x16GetStockHistoricalData\x12$.stock.GetStockHistoricalDataRequest\x1a%.stock.GetStockHistoricalDataResponse\x12Y\n" +
	"\x12GetStockQuoteBatch\x12 .stock.GetStockQuoteBatchRequest\x1a!.stock.GetStockQuoteBatchResponseB\x1bZ\x19fafnir/shared/pb/stock;pbb\x06proto3"

var (
	file_stock_proto_rawDescOnce sync.Once
	file_stock_proto_rawDescData []byte
)

func file_stock_proto_rawDescGZIP() []byte {
	file_stock_proto_rawDescOnce.Do(func() {
		file_stock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stock_proto_rawDesc), len(file_stock_proto_rawDesc)))
	})
	return file_stock_proto_rawDescData
}

var file_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_stock_proto_goTypes = []any{
	(*StockMetadata)(nil),                  // 0: stock.StockMetadata
	(*StockQuote)(nil),                     // 1: stock.StockQuote
	(*StockHistoricalData)(nil),            // 2: stock.StockHistoricalData
	(*GetStockMetadataRequest)(nil),        // 3: stock.GetStockMetadataRequest
	(*GetStockQuoteRequest)(nil),           // 4: stock.GetStockQuoteRequest
	(*GetStockHistoricalDataRequest)(nil),  // 5: stock.GetStockHistoricalDataRequest
	(*GetStockQuoteBatchRequest)(nil),      // 6: stock.GetStockQuoteBatchRequest
	(*GetStockMetadataResponse)(nil),       // 7: stock.GetStockMetadataResponse
	(*GetStockQuoteResponse)(nil),          // 8: stock.GetStockQuoteResponse
	(*GetStockHistoricalDataResponse)(nil), // 9: stock.GetStockHistoricalDataResponse
	(*GetStockQuoteBatchResponse)(nil),     // 10: stock.GetStockQuoteBatchResponse
	(base.ErrorCode)(0),                    // 11: base.ErrorCode
}
var file_stock_proto_depIdxs = []int32{
	0,  // 0: stock.GetStockMetadataResponse.data:type_name -> stock.StockMetadata
	11, // 1: stock.GetStockMetadataResponse.code:type_name -> base.ErrorCode
	1,  // 2: stock.GetStockQuoteResponse.data:type_name -> stock.StockQuote
	11, // 3: stock.GetStockQuoteResponse.code:type_name -> base.ErrorCode
	2,  // 4: stock.GetStockHistoricalDataResponse.data:type_name -> stock.StockHistoricalData
	11, // 5: stock.GetStockHistoricalDataResponse.code:type_name -> base.ErrorCode
	1,  // 6: stock.GetStockQuoteBatchResponse.data:type_name -> stock.StockQuote
	11, // 7: stock.GetStockQuoteBatchResponse.code:type_name -> base.ErrorCode
	3,  // 8: stock.StockService.GetStockMetadata:input_type -> stock.GetStockMetadataRequest
	4,  // 9: stock.StockService.GetStockQuote:input_type -> stock.GetStockQuoteRequest
	5,  // 10: stock.StockService.GetStockHistoricalData:input_type -> stock.GetStockHistoricalDataRequest
	6,  // 11: stock.StockService.GetStockQuoteBatch:input_type -> stock.GetStockQuoteBatchRequest
	7,  // 12: stock.StockService.GetStockMetadata:output_type -> stock.GetStockMetadataResponse
	8,  // 13: stock.StockService.GetStockQuote:output_type -> stock.GetStockQuoteResponse
	9,  // 14: stock.StockService.GetStockHistoricalData:output_type -> stock.GetStockHistoricalDataResponse
	10, // 15: stock.StockService.GetStockQuoteBatch:output_type -> stock.GetStockQuoteBatchResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_stock_proto_init() }
func file_stock_proto_init() {
	if File_stock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stock_proto_rawDesc), len(file_stock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stock_proto_goTypes,
		DependencyIndexes: file_stock_proto_depIdxs,
		MessageInfos:      file_stock_proto_msgTypes,
	}.Build()
	File_stock_proto = out.File
	file_stock_proto_goTypes = nil
	file_stock_proto_depIdxs = nil
}
