// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: stock.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StockService_GetStockMetadata_FullMethodName       = "/stock.StockService/GetStockMetadata"
	StockService_GetStockQuote_FullMethodName          = "/stock.StockService/GetStockQuote"
	StockService_GetStockHistoricalData_FullMethodName = "/stock.StockService/GetStockHistoricalData"
	StockService_GetStockQuoteBatch_FullMethodName     = "/stock.StockService/GetStockQuoteBatch"
)

// StockServiceClient is the client API for StockService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StockServiceClient interface {
	GetStockMetadata(ctx context.Context, in *GetStockMetadataRequest, opts ...grpc.CallOption) (*GetStockMetadataResponse, error)
	GetStockQuote(ctx context.Context, in *GetStockQuoteRequest, opts ...grpc.CallOption) (*GetStockQuoteResponse, error)
	GetStockHistoricalData(ctx context.Context, in *GetStockHistoricalDataRequest, opts ...grpc.CallOption) (*GetStockHistoricalDataResponse, error)
	GetStockQuoteBatch(ctx context.Context, in *GetStockQuoteBatchRequest, opts ...grpc.CallOption) (*GetStockQuoteBatchResponse, error)
}

type stockServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStockServiceClient(cc grpc.ClientConnInterface) StockServiceClient {
	return &stockServiceClient{cc}
}

func (c *stockServiceClient) GetStockMetadata(ctx context.Context, in *GetStockMetadataRequest, opts ...grpc.CallOption) (*GetStockMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStockMetadataResponse)
	err := c.cc.Invoke(ctx, StockService_GetStockMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockServiceClient) GetStockQuote(ctx context.Context, in *GetStockQuoteRequest, opts ...grpc.CallOption) (*GetStockQuoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStockQuoteResponse)
	err := c.cc.Invoke(ctx, StockService_GetStockQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockServiceClient) GetStockHistoricalData(ctx context.Context, in *GetStockHistoricalDataRequest, opts ...grpc.CallOption) (*GetStockHistoricalDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStockHistoricalDataResponse)
	err := c.cc.Invoke(ctx, StockService_GetStockHistoricalData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockServiceClient) GetStockQuoteBatch(ctx context.Context, in *GetStockQuoteBatchRequest, opts ...grpc.CallOption) (*GetStockQuoteBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStockQuoteBatchResponse)
	err := c.cc.Invoke(ctx, StockService_GetStockQuoteBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StockServiceServer is the server API for StockService service.
// All implementations must embed UnimplementedStockServiceServer
// for forward compatibility.
type StockServiceServer interface {
	GetStockMetadata(context.Context, *GetStockMetadataRequest) (*GetStockMetadataResponse, error)
	GetStockQuote(context.Context, *GetStockQuoteRequest) (*GetStockQuoteResponse, error)
	GetStockHistoricalData(context.Context, *GetStockHistoricalDataRequest) (*GetStockHistoricalDataResponse, error)
	GetStockQuoteBatch(context.Context, *GetStockQuoteBatchRequest) (*GetStockQuoteBatchResponse, error)
	mustEmbedUnimplementedStockServiceServer()
}

// UnimplementedStockServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStockServiceServer struct{}

func (UnimplementedStockServiceServer) GetStockMetadata(context.Context, *GetStockMetadataRequest) (*GetStockMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStockMetadata not implemented")
}
func (UnimplementedStockServiceServer) GetStockQuote(context.Context, *GetStockQuoteRequest) (*GetStockQuoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStockQuote not implemented")
}
func (UnimplementedStockServiceServer) GetStockHistoricalData(context.Context, *GetStockHistoricalDataRequest) (*GetStockHistoricalDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStockHistoricalData not implemented")
}
func (UnimplementedStockServiceServer) GetStockQuoteBatch(context.Context, *GetStockQuoteBatchRequest) (*GetStockQuoteBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStockQuoteBatch not implemented")
}
func (UnimplementedStockServiceServer) mustEmbedUnimplementedStockServiceServer() {}
func (UnimplementedStockServiceServer) testEmbeddedByValue()                      {}

// UnsafeStockServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StockServiceServer will
// result in compilation errors.
type UnsafeStockServiceServer interface {
	mustEmbedUnimplementedStockServiceServer()
}

func RegisterStockServiceServer(s grpc.ServiceRegistrar, srv StockServiceServer) {
	// If the following call pancis, it indicates UnimplementedStockServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StockService_ServiceDesc, srv)
}

func _StockService_GetStockMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStockMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServiceServer).GetStockMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockService_GetStockMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServiceServer).GetStockMetadata(ctx, req.(*GetStockMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockService_GetStockQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStockQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServiceServer).GetStockQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockService_GetStockQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServiceServer).GetStockQuote(ctx, req.(*GetStockQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockService_GetStockHistoricalData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStockHistoricalDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServiceServer).GetStockHistoricalData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockService_GetStockHistoricalData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServiceServer).GetStockHistoricalData(ctx, req.(*GetStockHistoricalDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockService_GetStockQuoteBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStockQuoteBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServiceServer).GetStockQuoteBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockService_GetStockQuoteBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServiceServer).GetStockQuoteBatch(ctx, req.(*GetStockQuoteBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StockService_ServiceDesc is the grpc.ServiceDesc for StockService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StockService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stock.StockService",
	HandlerType: (*StockServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStockMetadata",
			Handler:    _StockService_GetStockMetadata_Handler,
		},
		{
			MethodName: "GetStockQuote",
			Handler:    _StockService_GetStockQuote_Handler,
		},
		{
			MethodName: "GetStockHistoricalData",
			Handler:    _StockService_GetStockHistoricalData_Handler,
		},
		{
			MethodName: "GetStockQuoteBatch",
			Handler:    _StockService_GetStockQuoteBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stock.proto",
}
