// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type HasPermissionRequest struct {
	UserID     string `json:"userId"`
	Permission string `json:"permission"`
}

type HasPermissionResponse struct {
	Data *SecurityPermission `json:"data"`
	Code string              `json:"code"`
}

type ProfileData struct {
	UserID    string `json:"userId"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type ProfileDataResponse struct {
	Data *ProfileData `json:"data,omitempty"`
	Code string       `json:"code"`
}

type Query struct {
}

type SecurityPermission struct {
	HasPermission bool `json:"hasPermission"`
}

type StockData struct {
	Symbol           string `json:"symbol"`
	Name             string `json:"name"`
	Exchange         string `json:"exchange"`
	ExchangeFullName string `json:"exchangeFullName"`
	Currency         string `json:"currency"`
}

type StockHistoricalData struct {
	Symbol             string  `json:"symbol"`
	Date               string  `json:"date"`
	Open               float64 `json:"open"`
	High               float64 `json:"high"`
	Low                float64 `json:"low"`
	Close              float64 `json:"close"`
	Volume             int64   `json:"volume"`
	PriceChange        float64 `json:"priceChange"`
	PriceChangePercent float64 `json:"priceChangePercent"`
}

type StockHistoricalDataResponse struct {
	Code string                 `json:"code"`
	Data []*StockHistoricalData `json:"data,omitempty"`
}

type StockMetadataResponse struct {
	Code string     `json:"code"`
	Data *StockData `json:"data,omitempty"`
}

type StockPriceData struct {
	Symbol             string  `json:"symbol"`
	Price              float64 `json:"price"`
	Open               float64 `json:"open"`
	PreviousClose      float64 `json:"previousClose"`
	PriceChange        float64 `json:"priceChange"`
	PriceChangePercent float64 `json:"priceChangePercent"`
	Volume             int64   `json:"volume"`
	MarketCap          float64 `json:"marketCap"`
	DayLow             float64 `json:"dayLow"`
	DayHigh            float64 `json:"dayHigh"`
	YearHigh           float64 `json:"yearHigh"`
	YearLow            float64 `json:"yearLow"`
}

type StockQuoteBatchResponse struct {
	Code string            `json:"code"`
	Data []*StockPriceData `json:"data,omitempty"`
}

type StockQuoteResponse struct {
	Code string          `json:"code"`
	Data *StockPriceData `json:"data,omitempty"`
}
