// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CancelOrderResponse struct {
	Data *Order `json:"data,omitempty"`
	Code string `json:"code"`
}

type CreateOrderRequest struct {
	Symbol    string   `json:"symbol"`
	Side      string   `json:"side"`
	Type      string   `json:"type"`
	Quantity  float64  `json:"quantity"`
	Price     *float64 `json:"price,omitempty"`
	StopPrice *float64 `json:"stopPrice,omitempty"`
	Status    *string  `json:"status,omitempty"`
}

type CreateOrderResponse struct {
	Data *Order `json:"data,omitempty"`
	Code string `json:"code"`
}

type HasPermissionRequest struct {
	Permission string `json:"permission"`
}

type HasPermissionResponse struct {
	Data *SecurityPermission `json:"data"`
	Code string              `json:"code"`
}

type Mutation struct {
}

type Order struct {
	ID             string  `json:"id"`
	UserID         string  `json:"userId"`
	Symbol         string  `json:"symbol"`
	Side           string  `json:"side"`
	Type           string  `json:"type"`
	Status         string  `json:"status"`
	Quantity       float64 `json:"quantity"`
	Price          float64 `json:"price"`
	StopPrice      float64 `json:"stopPrice"`
	FilledQuantity float64 `json:"filledQuantity"`
	AvgFillPrice   float64 `json:"avgFillPrice"`
	CreatedAt      string  `json:"createdAt"`
	UpdatedAt      string  `json:"updatedAt"`
}

type OrdersResponse struct {
	Data  []*Order `json:"data,omitempty"`
	Count int32    `json:"count"`
	Code  string   `json:"code"`
}

type ProfileData struct {
	UserID    string `json:"userId"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type ProfileDataResponse struct {
	Data *ProfileData `json:"data,omitempty"`
	Code string       `json:"code"`
}

type Query struct {
}

type SecurityPermission struct {
	HasPermission bool `json:"hasPermission"`
}

type StockData struct {
	Symbol           string `json:"symbol"`
	Name             string `json:"name"`
	Exchange         string `json:"exchange"`
	ExchangeFullName string `json:"exchangeFullName"`
	Currency         string `json:"currency"`
}

type StockHistoricalData struct {
	Symbol             string  `json:"symbol"`
	Date               string  `json:"date"`
	Open               float64 `json:"open"`
	High               float64 `json:"high"`
	Low                float64 `json:"low"`
	Close              float64 `json:"close"`
	Volume             int64   `json:"volume"`
	PriceChange        float64 `json:"priceChange"`
	PriceChangePercent float64 `json:"priceChangePercent"`
}

type StockHistoricalDataResponse struct {
	Code string                 `json:"code"`
	Data []*StockHistoricalData `json:"data,omitempty"`
}

type StockMetadataResponse struct {
	Code string     `json:"code"`
	Data *StockData `json:"data,omitempty"`
}

type StockPriceData struct {
	Symbol             string  `json:"symbol"`
	Price              float64 `json:"price"`
	Open               float64 `json:"open"`
	PreviousClose      float64 `json:"previousClose"`
	PriceChange        float64 `json:"priceChange"`
	PriceChangePercent float64 `json:"priceChangePercent"`
	Volume             int64   `json:"volume"`
	MarketCap          float64 `json:"marketCap"`
	DayLow             float64 `json:"dayLow"`
	DayHigh            float64 `json:"dayHigh"`
	YearHigh           float64 `json:"yearHigh"`
	YearLow            float64 `json:"yearLow"`
}

type StockQuoteBatchResponse struct {
	Code string            `json:"code"`
	Data []*StockPriceData `json:"data,omitempty"`
}

type StockQuoteResponse struct {
	Code string          `json:"code"`
	Data *StockPriceData `json:"data,omitempty"`
}
