// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type HasPermissionRequest struct {
	UserID     string `json:"userId"`
	Permission string `json:"permission"`
}

type HasPermissionResponse struct {
	HasPermission  bool   `json:"hasPermission"`
	PermissionCode string `json:"permissionCode"`
}

type ProfileDataRequest struct {
	UserID string `json:"userId"`
}

type ProfileDataResponse struct {
	UserID         string `json:"userId"`
	FirstName      string `json:"firstName"`
	LastName       string `json:"lastName"`
	PermissionCode string `json:"permissionCode"`
}

type Query struct {
}
