// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: portfolio.proto

package portfolio

import (
	base "fafnir/shared/pb/base"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountType int32

const (
	AccountType_ACCOUNT_TYPE_UNSPECIFIED AccountType = 0
	AccountType_ACCOUNT_TYPE_SAVINGS     AccountType = 1
	AccountType_ACCOUNT_TYPE_INVESTMENT  AccountType = 2
	AccountType_ACCOUNT_TYPE_CHEQUING    AccountType = 3
)

// Enum value maps for AccountType.
var (
	AccountType_name = map[int32]string{
		0: "ACCOUNT_TYPE_UNSPECIFIED",
		1: "ACCOUNT_TYPE_SAVINGS",
		2: "ACCOUNT_TYPE_INVESTMENT",
		3: "ACCOUNT_TYPE_CHEQUING",
	}
	AccountType_value = map[string]int32{
		"ACCOUNT_TYPE_UNSPECIFIED": 0,
		"ACCOUNT_TYPE_SAVINGS":     1,
		"ACCOUNT_TYPE_INVESTMENT":  2,
		"ACCOUNT_TYPE_CHEQUING":    3,
	}
)

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_portfolio_proto_enumTypes[0].Descriptor()
}

func (AccountType) Type() protoreflect.EnumType {
	return &file_portfolio_proto_enumTypes[0]
}

func (x AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountType.Descriptor instead.
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{0}
}

type CurrencyType int32

const (
	CurrencyType_CURRENCY_TYPE_UNSPECIFIED CurrencyType = 0
	CurrencyType_CURRENCY_TYPE_USD         CurrencyType = 1
	CurrencyType_CURRENCY_TYPE_CAD         CurrencyType = 2
)

// Enum value maps for CurrencyType.
var (
	CurrencyType_name = map[int32]string{
		0: "CURRENCY_TYPE_UNSPECIFIED",
		1: "CURRENCY_TYPE_USD",
		2: "CURRENCY_TYPE_CAD",
	}
	CurrencyType_value = map[string]int32{
		"CURRENCY_TYPE_UNSPECIFIED": 0,
		"CURRENCY_TYPE_USD":         1,
		"CURRENCY_TYPE_CAD":         2,
	}
)

func (x CurrencyType) Enum() *CurrencyType {
	p := new(CurrencyType)
	*p = x
	return p
}

func (x CurrencyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CurrencyType) Descriptor() protoreflect.EnumDescriptor {
	return file_portfolio_proto_enumTypes[1].Descriptor()
}

func (CurrencyType) Type() protoreflect.EnumType {
	return &file_portfolio_proto_enumTypes[1]
}

func (x CurrencyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CurrencyType.Descriptor instead.
func (CurrencyType) EnumDescriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{1}
}

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountNumber string                 `protobuf:"bytes,3,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Type          AccountType            `protobuf:"varint,4,opt,name=type,proto3,enum=portfolio.AccountType" json:"type,omitempty"`
	Currency      CurrencyType           `protobuf:"varint,5,opt,name=currency,proto3,enum=portfolio.CurrencyType" json:"currency,omitempty"`
	Balance       float64                `protobuf:"fixed64,6,opt,name=balance,proto3" json:"balance,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_portfolio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Account) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *Account) GetType() AccountType {
	if x != nil {
		return x.Type
	}
	return AccountType_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *Account) GetCurrency() CurrencyType {
	if x != nil {
		return x.Currency
	}
	return CurrencyType_CURRENCY_TYPE_UNSPECIFIED
}

func (x *Account) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Account) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Account) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Holding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Quantity      float64                `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	AvgCost       float64                `protobuf:"fixed64,5,opt,name=avg_cost,json=avgCost,proto3" json:"avg_cost,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Holding) Reset() {
	*x = Holding{}
	mi := &file_portfolio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Holding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Holding) ProtoMessage() {}

func (x *Holding) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Holding.ProtoReflect.Descriptor instead.
func (*Holding) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{1}
}

func (x *Holding) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Holding) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Holding) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Holding) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Holding) GetAvgCost() float64 {
	if x != nil {
		return x.AvgCost
	}
	return 0
}

func (x *Holding) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Holding) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type WatchlistItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	AddedAt       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchlistItem) Reset() {
	*x = WatchlistItem{}
	mi := &file_portfolio_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchlistItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchlistItem) ProtoMessage() {}

func (x *WatchlistItem) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchlistItem.ProtoReflect.Descriptor instead.
func (*WatchlistItem) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{2}
}

func (x *WatchlistItem) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *WatchlistItem) GetAddedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AddedAt
	}
	return nil
}

type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          AccountType            `protobuf:"varint,2,opt,name=type,proto3,enum=portfolio.AccountType" json:"type,omitempty"`
	Currency      CurrencyType           `protobuf:"varint,3,opt,name=currency,proto3,enum=portfolio.CurrencyType" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_portfolio_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAccountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAccountRequest) GetType() AccountType {
	if x != nil {
		return x.Type
	}
	return AccountType_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *CreateAccountRequest) GetCurrency() CurrencyType {
	if x != nil {
		return x.Currency
	}
	return CurrencyType_CURRENCY_TYPE_UNSPECIFIED
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          base.ErrorCode         `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	Account       *Account               `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_portfolio_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAccountResponse) GetCode() base.ErrorCode {
	if x != nil {
		return x.Code
	}
	return base.ErrorCode(0)
}

func (x *CreateAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type GetPortfolioSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPortfolioSummaryRequest) Reset() {
	*x = GetPortfolioSummaryRequest{}
	mi := &file_portfolio_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPortfolioSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortfolioSummaryRequest) ProtoMessage() {}

func (x *GetPortfolioSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortfolioSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetPortfolioSummaryRequest) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{5}
}

func (x *GetPortfolioSummaryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPortfolioSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          base.ErrorCode         `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	Accounts      []*Account             `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	TotalBalance  float64                `protobuf:"fixed64,3,opt,name=total_balance,json=totalBalance,proto3" json:"total_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPortfolioSummaryResponse) Reset() {
	*x = GetPortfolioSummaryResponse{}
	mi := &file_portfolio_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPortfolioSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortfolioSummaryResponse) ProtoMessage() {}

func (x *GetPortfolioSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortfolioSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetPortfolioSummaryResponse) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{6}
}

func (x *GetPortfolioSummaryResponse) GetCode() base.ErrorCode {
	if x != nil {
		return x.Code
	}
	return base.ErrorCode(0)
}

func (x *GetPortfolioSummaryResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *GetPortfolioSummaryResponse) GetTotalBalance() float64 {
	if x != nil {
		return x.TotalBalance
	}
	return 0
}

type GetHoldingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHoldingsRequest) Reset() {
	*x = GetHoldingsRequest{}
	mi := &file_portfolio_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHoldingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHoldingsRequest) ProtoMessage() {}

func (x *GetHoldingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHoldingsRequest.ProtoReflect.Descriptor instead.
func (*GetHoldingsRequest) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{7}
}

func (x *GetHoldingsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetHoldingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          base.ErrorCode         `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	Holdings      []*Holding             `protobuf:"bytes,2,rep,name=holdings,proto3" json:"holdings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHoldingsResponse) Reset() {
	*x = GetHoldingsResponse{}
	mi := &file_portfolio_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHoldingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHoldingsResponse) ProtoMessage() {}

func (x *GetHoldingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHoldingsResponse.ProtoReflect.Descriptor instead.
func (*GetHoldingsResponse) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{8}
}

func (x *GetHoldingsResponse) GetCode() base.ErrorCode {
	if x != nil {
		return x.Code
	}
	return base.ErrorCode(0)
}

func (x *GetHoldingsResponse) GetHoldings() []*Holding {
	if x != nil {
		return x.Holdings
	}
	return nil
}

type GetHoldingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHoldingRequest) Reset() {
	*x = GetHoldingRequest{}
	mi := &file_portfolio_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHoldingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHoldingRequest) ProtoMessage() {}

func (x *GetHoldingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHoldingRequest.ProtoReflect.Descriptor instead.
func (*GetHoldingRequest) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{9}
}

func (x *GetHoldingRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetHoldingRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type GetHoldingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          base.ErrorCode         `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	Holding       *Holding               `protobuf:"bytes,2,opt,name=holding,proto3" json:"holding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHoldingResponse) Reset() {
	*x = GetHoldingResponse{}
	mi := &file_portfolio_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHoldingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHoldingResponse) ProtoMessage() {}

func (x *GetHoldingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHoldingResponse.ProtoReflect.Descriptor instead.
func (*GetHoldingResponse) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{10}
}

func (x *GetHoldingResponse) GetCode() base.ErrorCode {
	if x != nil {
		return x.Code
	}
	return base.ErrorCode(0)
}

func (x *GetHoldingResponse) GetHolding() *Holding {
	if x != nil {
		return x.Holding
	}
	return nil
}

type GetWatchlistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWatchlistRequest) Reset() {
	*x = GetWatchlistRequest{}
	mi := &file_portfolio_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWatchlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWatchlistRequest) ProtoMessage() {}

func (x *GetWatchlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWatchlistRequest.ProtoReflect.Descriptor instead.
func (*GetWatchlistRequest) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{11}
}

func (x *GetWatchlistRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetWatchlistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          base.ErrorCode         `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	Items         []*WatchlistItem       `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWatchlistResponse) Reset() {
	*x = GetWatchlistResponse{}
	mi := &file_portfolio_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWatchlistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWatchlistResponse) ProtoMessage() {}

func (x *GetWatchlistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWatchlistResponse.ProtoReflect.Descriptor instead.
func (*GetWatchlistResponse) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{12}
}

func (x *GetWatchlistResponse) GetCode() base.ErrorCode {
	if x != nil {
		return x.Code
	}
	return base.ErrorCode(0)
}

func (x *GetWatchlistResponse) GetItems() []*WatchlistItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type AddToWatchlistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToWatchlistRequest) Reset() {
	*x = AddToWatchlistRequest{}
	mi := &file_portfolio_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToWatchlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToWatchlistRequest) ProtoMessage() {}

func (x *AddToWatchlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToWatchlistRequest.ProtoReflect.Descriptor instead.
func (*AddToWatchlistRequest) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{13}
}

func (x *AddToWatchlistRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddToWatchlistRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type AddToWatchlistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          base.ErrorCode         `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToWatchlistResponse) Reset() {
	*x = AddToWatchlistResponse{}
	mi := &file_portfolio_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToWatchlistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToWatchlistResponse) ProtoMessage() {}

func (x *AddToWatchlistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToWatchlistResponse.ProtoReflect.Descriptor instead.
func (*AddToWatchlistResponse) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{14}
}

func (x *AddToWatchlistResponse) GetCode() base.ErrorCode {
	if x != nil {
		return x.Code
	}
	return base.ErrorCode(0)
}

type RemoveFromWatchlistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromWatchlistRequest) Reset() {
	*x = RemoveFromWatchlistRequest{}
	mi := &file_portfolio_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromWatchlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromWatchlistRequest) ProtoMessage() {}

func (x *RemoveFromWatchlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromWatchlistRequest.ProtoReflect.Descriptor instead.
func (*RemoveFromWatchlistRequest) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{15}
}

func (x *RemoveFromWatchlistRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveFromWatchlistRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type RemoveFromWatchlistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          base.ErrorCode         `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromWatchlistResponse) Reset() {
	*x = RemoveFromWatchlistResponse{}
	mi := &file_portfolio_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromWatchlistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromWatchlistResponse) ProtoMessage() {}

func (x *RemoveFromWatchlistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromWatchlistResponse.ProtoReflect.Descriptor instead.
func (*RemoveFromWatchlistResponse) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{16}
}

func (x *RemoveFromWatchlistResponse) GetCode() base.ErrorCode {
	if x != nil {
		return x.Code
	}
	return base.ErrorCode(0)
}

type DeleteAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountRequest) Reset() {
	*x = DeleteAccountRequest{}
	mi := &file_portfolio_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountRequest) ProtoMessage() {}

func (x *DeleteAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type DeleteAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          base.ErrorCode         `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountResponse) Reset() {
	*x = DeleteAccountResponse{}
	mi := &file_portfolio_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountResponse) ProtoMessage() {}

func (x *DeleteAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountResponse.ProtoReflect.Descriptor instead.
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteAccountResponse) GetCode() base.ErrorCode {
	if x != nil {
		return x.Code
	}
	return base.ErrorCode(0)
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,6,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_portfolio_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{19}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Transaction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Transaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Transaction) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *Transaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsRequest) Reset() {
	*x = GetTransactionsRequest{}
	mi := &file_portfolio_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsRequest) ProtoMessage() {}

func (x *GetTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{20}
}

func (x *GetTransactionsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          base.ErrorCode         `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	Transactions  []*Transaction         `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsResponse) Reset() {
	*x = GetTransactionsResponse{}
	mi := &file_portfolio_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsResponse) ProtoMessage() {}

func (x *GetTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{21}
}

func (x *GetTransactionsResponse) GetCode() base.ErrorCode {
	if x != nil {
		return x.Code
	}
	return base.ErrorCode(0)
}

func (x *GetTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_portfolio_proto protoreflect.FileDescriptor

const file_portfolio_proto_rawDesc = "" +
	"\n" +
	"\x0fportfolio.proto\x12\tportfolio\x1a\n" +
	"base.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xca\x02\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12%\n" +
	"\x0eaccount_number\x18\x03 \x01(\tR\raccountNumber\x12*\n" +
	"\x04type\x18\x04 \x01(\x0e2\x16.portfolio.AccountTypeR\x04type\x123\n" +
	"\bcurrency\x18\x05 \x01(\x0e2\x17.portfolio.CurrencyTypeR\bcurrency\x12\x18\n" +
	"\abalance\x18\x06 \x01(\x01R\abalance\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xfd\x01\n" +
	"\aHolding\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\x12\x19\n" +
	"\bavg_cost\x18\x05 \x01(\x01R\aavgCost\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"^\n" +
	"\rWatchlistItem\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x125\n" +
	"\badded_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aaddedAt\"\x90\x01\n" +
	"\x14CreateAccountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12*\n" +
	"\x04type\x18\x02 \x01(\x0e2\x16.portfolio.AccountTypeR\x04type\x123\n" +
	"\bcurrency\x18\x03 \x01(\x0e2\x17.portfolio.CurrencyTypeR\bcurrency\"j\n" +
	"\x15CreateAccountResponse\x12#\n" +
	"\x04code\x18\x01 \x01(\x0e2\x0f.base.ErrorCodeR\x04code\x12,\n" +
	"\aaccount\x18\x02 \x01(\v2\x12.portfolio.AccountR\aaccount\"5\n" +
	"\x1aGetPortfolioSummaryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x97\x01\n" +
	"\x1bGetPortfolioSummaryResponse\x12#\n" +
	"\x04code\x18\x01 \x01(\x0e2\x0f.base.ErrorCodeR\x04code\x12.\n" +
	"\baccounts\x18\x02 \x03(\v2\x12.portfolio.AccountR\baccounts\x12#\n" +
	"\rtotal_balance\x18\x03 \x01(\x01R\ftotalBalance\"3\n" +
	"\x12GetHoldingsRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"j\n" +
	"\x13GetHoldingsResponse\x12#\n" +
	"\x04code\x18\x01 \x01(\x0e2\x0f.base.ErrorCodeR\x04code\x12.\n" +
	"\bholdings\x18\x02 \x03(\v2\x12.portfolio.HoldingR\bholdings\"J\n" +
	"\x11GetHoldingRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\"g\n" +
	"\x12GetHoldingResponse\x12#\n" +
	"\x04code\x18\x01 \x01(\x0e2\x0f.base.ErrorCodeR\x04code\x12,\n" +
	"\aholding\x18\x02 \x01(\v2\x12.portfolio.HoldingR\aholding\".\n" +
	"\x13GetWatchlistRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"k\n" +
	"\x14GetWatchlistResponse\x12#\n" +
	"\x04code\x18\x01 \x01(\x0e2\x0f.base.ErrorCodeR\x04code\x12.\n" +
	"\x05items\x18\x02 \x03(\v2\x18.portfolio.WatchlistItemR\x05items\"H\n" +
	"\x15AddToWatchlistRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\"=\n" +
	"\x16AddToWatchlistResponse\x12#\n" +
	"\x04code\x18\x01 \x01(\x0e2\x0f.base.ErrorCodeR\x04code\"M\n" +
	"\x1aRemoveFromWatchlistRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\"B\n" +
	"\x1bRemoveFromWatchlistResponse\x12#\n" +
	"\x04code\x18\x01 \x01(\x0e2\x0f.base.ErrorCodeR\x04code\"5\n" +
	"\x14DeleteAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"<\n" +
	"\x15DeleteAccountResponse\x12#\n" +
	"\x04code\x18\x01 \x01(\x0e2\x0f.base.ErrorCodeR\x04code\"\xe8\x01\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12!\n" +
	"\freference_id\x18\x06 \x01(\tR\vreferenceId\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"7\n" +
	"\x16GetTransactionsRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"z\n" +
	"\x17GetTransactionsResponse\x12#\n" +
	"\x04code\x18\x01 \x01(\x0e2\x0f.base.ErrorCodeR\x04code\x12:\n" +
	"\ftransactions\x18\x02 \x03(\v2\x16.portfolio.TransactionR\ftransactions*}\n" +
	"\vAccountType\x12\x1c\n" +
	"\x18ACCOUNT_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ACCOUNT_TYPE_SAVINGS\x10\x01\x12\x1b\n" +
	"\x17ACCOUNT_TYPE_INVESTMENT\x10\x02\x12\x19\n" +
	"\x15ACCOUNT_TYPE_CHEQUING\x10\x03*[\n" +
	"\fCurrencyType\x12\x1d\n" +
	"\x19CURRENCY_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11CURRENCY_TYPE_USD\x10\x01\x12\x15\n" +
	"\x11CURRENCY_TYPE_CAD\x10\x022\xa1\x06\n" +
	"\x10PortfolioService\x12R\n" +
	"\rCreateAccount\x12\x1f.portfolio.CreateAccountRequest\x1a .portfolio.CreateAccountResponse\x12d\n" +
	"\x13GetPortfolioSummary\x12%.portfolio.GetPortfolioSummaryRequest\x1a&.portfolio.GetPortfolioSummaryResponse\x12L\n" +
	"\vGetHoldings\x12\x1d.portfolio.GetHoldingsRequest\x1a\x1e.portfolio.GetHoldingsResponse\x12I\n" +
	"\n" +
	"GetHolding\x12\x1c.portfolio.GetHoldingRequest\x1a\x1d.portfolio.GetHoldingResponse\x12O\n" +
	"\fGetWatchlist\x12\x1e.portfolio.GetWatchlistRequest\x1a\x1f.portfolio.GetWatchlistResponse\x12U\n" +
	"\x0eAddToWatchlist\x12 .portfolio.AddToWatchlistRequest\x1a!.portfolio.AddToWatchlistResponse\x12d\n" +
	"\x13RemoveFromWatchlist\x12%.portfolio.RemoveFromWatchlistRequest\x1a&.portfolio.RemoveFromWatchlistResponse\x12R\n" +
	"\rDeleteAccount\x12\x1f.portfolio.DeleteAccountRequest\x1a .portfolio.DeleteAccountResponse\x12X\n" +
	"\x0fGetTransactions\x12!.portfolio.GetTransactionsRequest\x1a\".portfolio.GetTransactionsResponseB\x1cZ\x1afafnir/shared/pb/portfoliob\x06proto3"

var (
	file_portfolio_proto_rawDescOnce sync.Once
	file_portfolio_proto_rawDescData []byte
)

func file_portfolio_proto_rawDescGZIP() []byte {
	file_portfolio_proto_rawDescOnce.Do(func() {
		file_portfolio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_portfolio_proto_rawDesc), len(file_portfolio_proto_rawDesc)))
	})
	return file_portfolio_proto_rawDescData
}

var file_portfolio_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_portfolio_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_portfolio_proto_goTypes = []any{
	(AccountType)(0),                    // 0: portfolio.AccountType
	(CurrencyType)(0),                   // 1: portfolio.CurrencyType
	(*Account)(nil),                     // 2: portfolio.Account
	(*Holding)(nil),                     // 3: portfolio.Holding
	(*WatchlistItem)(nil),               // 4: portfolio.WatchlistItem
	(*CreateAccountRequest)(nil),        // 5: portfolio.CreateAccountRequest
	(*CreateAccountResponse)(nil),       // 6: portfolio.CreateAccountResponse
	(*GetPortfolioSummaryRequest)(nil),  // 7: portfolio.GetPortfolioSummaryRequest
	(*GetPortfolioSummaryResponse)(nil), // 8: portfolio.GetPortfolioSummaryResponse
	(*GetHoldingsRequest)(nil),          // 9: portfolio.GetHoldingsRequest
	(*GetHoldingsResponse)(nil),         // 10: portfolio.GetHoldingsResponse
	(*GetHoldingRequest)(nil),           // 11: portfolio.GetHoldingRequest
	(*GetHoldingResponse)(nil),          // 12: portfolio.GetHoldingResponse
	(*GetWatchlistRequest)(nil),         // 13: portfolio.GetWatchlistRequest
	(*GetWatchlistResponse)(nil),        // 14: portfolio.GetWatchlistResponse
	(*AddToWatchlistRequest)(nil),       // 15: portfolio.AddToWatchlistRequest
	(*AddToWatchlistResponse)(nil),      // 16: portfolio.AddToWatchlistResponse
	(*RemoveFromWatchlistRequest)(nil),  // 17: portfolio.RemoveFromWatchlistRequest
	(*RemoveFromWatchlistResponse)(nil), // 18: portfolio.RemoveFromWatchlistResponse
	(*DeleteAccountRequest)(nil),        // 19: portfolio.DeleteAccountRequest
	(*DeleteAccountResponse)(nil),       // 20: portfolio.DeleteAccountResponse
	(*Transaction)(nil),                 // 21: portfolio.Transaction
	(*GetTransactionsRequest)(nil),      // 22: portfolio.GetTransactionsRequest
	(*GetTransactionsResponse)(nil),     // 23: portfolio.GetTransactionsResponse
	(*timestamppb.Timestamp)(nil),       // 24: google.protobuf.Timestamp
	(base.ErrorCode)(0),                 // 25: base.ErrorCode
}
var file_portfolio_proto_depIdxs = []int32{
	0,  // 0: portfolio.Account.type:type_name -> portfolio.AccountType
	1,  // 1: portfolio.Account.currency:type_name -> portfolio.CurrencyType
	24, // 2: portfolio.Account.created_at:type_name -> google.protobuf.Timestamp
	24, // 3: portfolio.Account.updated_at:type_name -> google.protobuf.Timestamp
	24, // 4: portfolio.Holding.created_at:type_name -> google.protobuf.Timestamp
	24, // 5: portfolio.Holding.updated_at:type_name -> google.protobuf.Timestamp
	24, // 6: portfolio.WatchlistItem.added_at:type_name -> google.protobuf.Timestamp
	0,  // 7: portfolio.CreateAccountRequest.type:type_name -> portfolio.AccountType
	1,  // 8: portfolio.CreateAccountRequest.currency:type_name -> portfolio.CurrencyType
	25, // 9: portfolio.CreateAccountResponse.code:type_name -> base.ErrorCode
	2,  // 10: portfolio.CreateAccountResponse.account:type_name -> portfolio.Account
	25, // 11: portfolio.GetPortfolioSummaryResponse.code:type_name -> base.ErrorCode
	2,  // 12: portfolio.GetPortfolioSummaryResponse.accounts:type_name -> portfolio.Account
	25, // 13: portfolio.GetHoldingsResponse.code:type_name -> base.ErrorCode
	3,  // 14: portfolio.GetHoldingsResponse.holdings:type_name -> portfolio.Holding
	25, // 15: portfolio.GetHoldingResponse.code:type_name -> base.ErrorCode
	3,  // 16: portfolio.GetHoldingResponse.holding:type_name -> portfolio.Holding
	25, // 17: portfolio.GetWatchlistResponse.code:type_name -> base.ErrorCode
	4,  // 18: portfolio.GetWatchlistResponse.items:type_name -> portfolio.WatchlistItem
	25, // 19: portfolio.AddToWatchlistResponse.code:type_name -> base.ErrorCode
	25, // 20: portfolio.RemoveFromWatchlistResponse.code:type_name -> base.ErrorCode
	25, // 21: portfolio.DeleteAccountResponse.code:type_name -> base.ErrorCode
	24, // 22: portfolio.Transaction.created_at:type_name -> google.protobuf.Timestamp
	25, // 23: portfolio.GetTransactionsResponse.code:type_name -> base.ErrorCode
	21, // 24: portfolio.GetTransactionsResponse.transactions:type_name -> portfolio.Transaction
	5,  // 25: portfolio.PortfolioService.CreateAccount:input_type -> portfolio.CreateAccountRequest
	7,  // 26: portfolio.PortfolioService.GetPortfolioSummary:input_type -> portfolio.GetPortfolioSummaryRequest
	9,  // 27: portfolio.PortfolioService.GetHoldings:input_type -> portfolio.GetHoldingsRequest
	11, // 28: portfolio.PortfolioService.GetHolding:input_type -> portfolio.GetHoldingRequest
	13, // 29: portfolio.PortfolioService.GetWatchlist:input_type -> portfolio.GetWatchlistRequest
	15, // 30: portfolio.PortfolioService.AddToWatchlist:input_type -> portfolio.AddToWatchlistRequest
	17, // 31: portfolio.PortfolioService.RemoveFromWatchlist:input_type -> portfolio.RemoveFromWatchlistRequest
	19, // 32: portfolio.PortfolioService.DeleteAccount:input_type -> portfolio.DeleteAccountRequest
	22, // 33: portfolio.PortfolioService.GetTransactions:input_type -> portfolio.GetTransactionsRequest
	6,  // 34: portfolio.PortfolioService.CreateAccount:output_type -> portfolio.CreateAccountResponse
	8,  // 35: portfolio.PortfolioService.GetPortfolioSummary:output_type -> portfolio.GetPortfolioSummaryResponse
	10, // 36: portfolio.PortfolioService.GetHoldings:output_type -> portfolio.GetHoldingsResponse
	12, // 37: portfolio.PortfolioService.GetHolding:output_type -> portfolio.GetHoldingResponse
	14, // 38: portfolio.PortfolioService.GetWatchlist:output_type -> portfolio.GetWatchlistResponse
	16, // 39: portfolio.PortfolioService.AddToWatchlist:output_type -> portfolio.AddToWatchlistResponse
	18, // 40: portfolio.PortfolioService.RemoveFromWatchlist:output_type -> portfolio.RemoveFromWatchlistResponse
	20, // 41: portfolio.PortfolioService.DeleteAccount:output_type -> portfolio.DeleteAccountResponse
	23, // 42: portfolio.PortfolioService.GetTransactions:output_type -> portfolio.GetTransactionsResponse
	34, // [34:43] is the sub-list for method output_type
	25, // [25:34] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_portfolio_proto_init() }
func file_portfolio_proto_init() {
	if File_portfolio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_portfolio_proto_rawDesc), len(file_portfolio_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_portfolio_proto_goTypes,
		DependencyIndexes: file_portfolio_proto_depIdxs,
		EnumInfos:         file_portfolio_proto_enumTypes,
		MessageInfos:      file_portfolio_proto_msgTypes,
	}.Build()
	File_portfolio_proto = out.File
	file_portfolio_proto_goTypes = nil
	file_portfolio_proto_depIdxs = nil
}
