services:
  prometheus:
    image: prom/prometheus:latest
    container_name: fafnir-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - ../../infra/monitoring/prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - fafnir-network

  grafana:
    image: grafana/grafana:latest
    container_name: fafnir-grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_ADMIN_PASS:-admin}
      GF_USERS_ALLOW_SIGN_UP: false
    volumes:
      - ../../infra/monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ../../infra/monitoring/grafana/dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana
    networks:
      - fafnir-network
    depends_on:
      - prometheus

volumes:
  prom_data:
    driver: local
  grafana_data:
    driver: local

networks:
  fafnir-network:
    driver: bridge
